### ISSUE TITLE
azure API limits returns first 50 results

### ISSUE THREAD

**Issue by MarianoRubio** [Azure/azure_preview_modules#203]
Azure API limits return to 50 results, need to make the page limit when wrapping an API call transparent. Otherwise azure_rm_resource_facts works when you have less than 50 resources...
Anyone faces the same issue?

**Comment by Fred-sun** [comment]
@yungezz Could you please take a look this question when you're available? Thanks!

**Comment by yungezz** [comment]
@MarianoRubio  which Azure API are you using? if the api paged? you might want to iterate next_page_token . Is this a general Azure question or Ansible on Azure issue?

**Comment by MarianoRubio** [comment]
@yungezz 

API version is 2018-10-01, and yes it is paged, (Are there non paged versions? that would short it) I would say Ansible as the API paging the results is common but the module should be the one handling that loop until next_page_token is empty.

**Comment by MarianoRubio** [comment]
> @MarianoRubio which Azure API are you using? if the api paged? you might want to iterate next_page_token . Is this a general Azure question or Ansible on Azure issue?

**Comment by MarianoRubio** [comment]
- Closed by mistake sorry

**Comment by yungezz** [comment]
@MarianoRubio  are you using azure_rm_resource module?

**Comment by MarianoRubio** [comment]
Hi @yungezz  im using literally like bellow.

- name: Get instances
   azure_rm_resource_facts:
        api_version: "2018-10-01"
        provider: compute
        resource_type: virtualmachines
        cert_validation_mode: "ignore"
    register: instance_facts

**Comment by yungezz** [comment]
HI @zikalino could you pls look at the paging issue in azure_rm_resource_facts?

**Comment by zikalino** [comment]
@yungezz @MarianoRubio I will fix it asap

**Comment by zikalino** [comment]
@MarianoRubio I already know how this should be fixed, however I am having some problems reproducing this issue. Basically I am trying to query resources, and I am getting responses with more than 50 items without paging:

My current playbook looks like this:
```yaml
  - name: Query Subnets
    azure_rm_resource_facts:
      api_version: '2018-08-01'
      resource_group: "{{ resource_group }}"
      provider: network
      resource_type: virtualnetworks
      resource_name: myvn
      subresource:
        - type: subnets
    register: output
  - debug:
      msg: list lenght {{ output['response'][0]['value'] | length }}

  - name: Query virtual machines in subscription
    azure_rm_resource_facts:
      api_version: '2018-10-01'
      provider: compute
      resource_type: virtualmachines
    register: output

  - debug:
      msg: list lenght {{ output['response'][0]['value'] | length }}
```

and response

```
TASK [Query Subnets] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "list length 60"
}

TASK [Query virtual machines in subscription] *******************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "list length 54"
}

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
