### ISSUE TITLE
Proposal / Request - Re-enable pip task

### ISSUE THREAD

**Issue by coreywan** [Azure/azure_preview_modules#237]
I would like to propose an update to the `tasks/main.yml` file.  The current commented out task for installing the pip requirements is very very useful.  This is especially true when we are talking about using this role in a green field environment, where the Ansible worker nodes may be ephemeral and the python modules you are requiring may not be loaded up at the time of running.

The suggestion is to change the task to be:
```yaml
- name: Install Azure Python SDK required by modules.
  pip:
    requirements: "{{ role_path }}/files/requirements-azure.txt"
    extra_args: -I
  when: skip_azure_sdk
``` 
Then also add the following into `defaults/main.yml` to make `skip_azure_sdk` a default of true, unless the playbook calling the role states otherwise.
```yaml
---
skip_azure_sdk: true
```

If you don't like that method, you could also create a new tasks file (IE `tasks/setup.yaml`) and the contents of that file just be:
```yaml
---
- name: Install Azure Python SDK required by modules.
  pip:
    requirements: "{{ role_path }}/files/requirements-azure.txt"
    extra_args: -I
```

Then the playbook developer could just write a play like so:
```yaml
---
- hosts: localhost
  tasks:
    - include_role:
         name: azure_preview_modules
         tasks_from: setup.yaml
```

That way the pip command is never ran unless someone explicitly calls for that task file to be used.

After gathering your thoughts, I could create the PR for it if you would like.
