### ISSUE TITLE
Feature Request - Add a parameter for specifying backend pool of LoadBalancer while creating VMSS 

### ISSUE THREAD

**Issue by IMG-PRCSNG** [Azure/azure_preview_modules#241]
The `az` cli allows for creating a VMSS that references an already existing load balancer by its **name** and the **backend pool** - [Docs](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#create-a-scale-set-that-references-an-existing-azure-load-balancer)

Can this be considered? Our use case is to manage multiple VMSS on the same load balancer - say, for example, staging and production - using ansible. Right now, it always defaults to 'default' or the first backend pool available on the load balancer.

The workaround we follow is to manage VMSS separately but then that defeats the purpose of using something like Ansible for provisioning.

Any other suggestions / workarounds?

**Comment by Fred-sun** [comment]
@IMG-PRCSNG Thanks for your reporting!

**Comment by Fred-sun** [comment]
@zikalino Please you help take a look this issue when you're available! Thanks!

**Comment by yuwzho** [comment]
This is already supported in Ansible 2.5

@Fred-sun Please give an example

**Comment by yuwzho** [comment]
Also can refer the example:

https://github.com/ansible/ansible/blob/b0cc3072dc589cd06341689c48d53bbe10c22385/test/integration/targets/azure_rm_virtualmachinescaleset/tasks/main.yml#L139-L166

**Comment by Fred-sun** [comment]
Hi @yuwei, azure_rm_virtualmachinescaleset can only specify load_balancer to be used. and back end pool of LoadBalancer cannot be specified. the supported parameters include:
```e.g.
include: ad_user, adfs_authority_url, admin_password, admin_username, api_profile, append_tags, auth_source, capacity, cert_validation_mode, client_id, cloud_environment, custom_data, data_disks, enable_accelerated_networking, image, load_balancer, location, managed_disk_type, name, os_disk_caching, os_type, overprovision, password, profile, remove_on_absent, resource_group, secret, security_group, short_hostname, ssh_password_enabled, ssh_public_keys, state, subnet_name, subscription_id, tags, tenant, tier, upgrade_policy, virtual_network_name, virtual_network_resource_group, vm_size, zones"

**Comment by IMG-PRCSNG** [comment]
Hi @yuwzho, 

Kindly look at the following example copied from [Azure documentaiton](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#create-a-scale-set-that-references-an-existing-azure-load-balancer), where I can create a load balancer with a custom backend pool by specifying *--backend-pool-name* and reference the load balancer and the backend pool while creating a VMSS using the cli parameter *--lb* and *--backend-pool-name* respectively. 

```bash
az network lb create \
    -g lbtest \
    -n mylb \
    --vnet-name myvnet \
    --subnet mysubnet \
    --public-ip-address-allocation Static \
    --backend-pool-name mybackendpool

az vmss create \
    -g lbtest \
    -n myvmss \
    --image Canonical:UbuntuServer:16.04-LTS:latest \
    --admin-username negat \
    --ssh-key-value /home/myuser/.ssh/id_rsa.pub \
    --upgrade-policy-mode Automatic \
    --instance-count 3 \
    --vnet-name myvnet \
    --subnet mysubnet \
    --lb mylb \
    --backend-pool-name mybackendpool
```

I am particularly looking at the possibility of specifying *backend pool name* as I would like to create two backend pools on the load balancer and reference the respective backend pool while creating the two VMSS. 

Right now, it is not possible as the `azurerm_virutalmachinescaleset` module accepts only the *load_balancer* parameter and internally picks the first backed pool and this will result in a conflict as two different VMSS are being added to the same backend pool by default.

**Comment by yuwzho** [comment]
@IMG-PRCSNG I see, I got your point, please correct me if anything wrong.

One of your Load Balancer has more than one `backend_address_pools`, and you wanna associate each of them to difference VMSS or availability set, but in our VMSS module, simply attach the whole `backend_address_pools` list to the VMSS instance. Right?

**Comment by IMG-PRCSNG** [comment]
That is accurate.

**Comment by Fred-sun** [comment]
@zikalino Could you help take a look this issue when you're available!? Thanks!

**Comment by MyronFanQiu** [comment]
HI @IMG-PRCSNG , I'm very sorry for the delay. We are occupied by some works last month. I create a branch with the `backend-pool-name` in https://github.com/Azure/azure_preview_modules/tree/vmss-backend-pool-name .You can have a test on it.

To use the specific branch, you need to 
1. Install this branch using `ansible-galaxy install git+https://github.com/Azure/azure_preview_modules,vmss-backend-pool-name`. 
2. In the playbook, refer `role: azure_preview_modules` rather than `role: azure.azure_preview_modules`.
3. In case you create a virtual env and need to upgrade the Python SDK, you can do
`pip install -r ~/.ansible/roles/azure_preview_modules/files/requirements-azure.txt`

There is an example for usage.
```
- name: Create VMSS
    azure_rm_virtualmachinescaleset:
      resource_group: myResourceGroup
      name: testVMSS0506
      vm_size: Standard_B1s
      admin_username: testuser
      ssh_password_enabled: true
      admin_password: "Password1234!"
      capacity: 1
      virtual_network_name: testVnet
      subnet_name: testSubnet
      upgrade_policy: Manual
      load_balancer: testLB1
      backend_pool_name: abcd
      tier: Standard
      managed_disk_type: Standard_LRS
      os_disk_caching: ReadWrite
      custom_data: "#cloud-config"
      image:
        offer: CoreOS
        publisher: CoreOS
        sku: Stable
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 64
          caching: ReadWrite
          managed_disk_type: Standard_LRS
```
Currently, it only supports setting one backend-pool-name. If you meet any problem or issue, please be free to contact me. Thanks again for opening this issue.
