### ISSUE TITLE
Creating LoadBalancer fails with __init__() takes exactly 1 argument (2 given).

### ISSUE THREAD

**Issue by elvinasp** [Azure/azure_preview_modules#253]
Hello, 

while trying to create LoadBalancer resource in AzureStack Ansible run fails with the Python error. Ansible playbooks works perfectly against AzureCloud, however our target environment is AzureStack and we are using AzureCloud only for temporary development.

UPDATE: It seems I was missing `- { role: azure.azure_preview_modules }` in my playbook. After I have added it, I was immediately greeted API not found error so API compatibility issues are the same as for Ansible Azure modules.

When using Ansible Azure modules I have been facing API version compatibility issues. By changing hardcoded versions in Azure modules or switching to Azure preview modules, allowed to solve the API version issue. However both Azure and Azure Preview modules fails with  __init__() takes exactly 1 argument (2 given)"` error, when creating LoadBalancer.

`fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/AnsiballZ_azure_rm_loadbalancer.py\", line 261, in <module>\n    _ansiballz_main()\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/AnsiballZ_azure_rm_loadbalancer.py\", line 251, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/AnsiballZ_azure_rm_loadbalancer.py\", line 119, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_JDUoLJ/__main__.py\", line 981, in <module>\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_JDUoLJ/__main__.py\", line 977, in main\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_JDUoLJ/__main__.py\", line 624, in __init__\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_JDUoLJ/ansible_azure_rm_loadbalancer_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_JDUoLJ/__main__.py\", line 738, in exec_module\nTypeError: __init__() takes exactly 1 argument (2 given)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`
When trying to rerun temporary payload it now gives the error below. I have looked at the file and at exploded temporary payload file contents, however my Python foo is not strong enough to identify the issue.

`Traceback (most recent call last):
  File "./AnsiballZ_azure_rm_loadbalancer.py", line 261, in <module>
    _ansiballz_main()
  File "./AnsiballZ_azure_rm_loadbalancer.py", line 248, in _ansiballz_main
    exitcode = debug(sys.argv[1], zipped_mod, ANSIBALLZ_PARAMS)
  File "./AnsiballZ_azure_rm_loadbalancer.py", line 216, in debug
    importer = imp.load_module('__main__', f, script_path, ('.py', 'r', imp.PY_SOURCE))
  File "/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/debug_dir/__main__.py", line 981, in <module>
    main()
  File "/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/debug_dir/__main__.py", line 977, in main
    AzureRMLoadBalancer()
  File "/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/debug_dir/__main__.py", line 624, in __init__
    supports_check_mode=True
  File "/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/debug_dir/ansible/module_utils/azure_rm_common.py", line 308, in __init__
    res = self.exec_module(**self.module.params)
  File "/home/atlas-admin/.ansible/tmp/ansible-tmp-1556604815.54-67422344188759/debug_dir/__main__.py", line 738, in exec_module
    ) for item in self.inbound_nat_pools] if self.inbound_nat_pools else None
TypeError: __init__() takes exactly 1 argument (2 given)
`

Environment:
OS: Ubuntu 18.04.1 LTS
Ansible: 
`ansible 2.7.9
  config file = None
  configured module search path = [u'/home/atlas-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]`
Azure preview modules installed as defined in <https://galaxy.ansible.com/Azure/azure_preview_modules>
AzureStack: 1903

Load balancer definition (snip from the role):
```yaml
- name: Create Load Balancer
  azure_rm_loadbalancer:
    name: "{{ definedLoadbalancer }}"
    resource_group:  "{{ resourceGroup }}"
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: "{{ definedPublicipaddress }}"
    probes:
      - name: probhttp
        port: 32080
        protocol: Tcp
        interval: 10
        fail_count: 3
      - name: probhttps
        port: 32443
        protocol: Tcp
        interval: 10
        fail_count: 3
    backend_address_pools:
      - name: "{{ definedLBBackendpool }}"
    inbound_nat_pools:
      - name: inboundnatpool0
        frontend_ip_configuration_name: frontendipconf0
        protocol: Tcp
        frontend_port_range_start: 80
        frontend_port_range_end: 81
        backend_port: 8080
    load_balancing_rules:
      - name: lbrbalancingrulehttp
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: "{{ definedLBBackendpool }}"
        frontend_port: 80
        backend_port: 32080
        probe: probhttp
      - name: lbrbalancingrulehttps
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: "{{ definedLBBackendpool }}"
        frontend_port: 443
        backend_port: 32443
        probe: probhttps
    sku: Basic
````
