### ISSUE TITLE
azure_rm_sqldatabase parameter elastic_pool_name is ignored

### ISSUE THREAD

**Issue by jxn** [Azure/azure_preview_modules#268]
I'm using the modules to create 1) SQL Server, 2) Elastic Pool, and then 3) Database

However, while all the resources are created, this elastic_pool_name parameter doesn't seem to be used, as my created database always shows up as "No elastic pool" in azure after the playbook has run.  No errors are shown.  Ansible 2.8.0, preview modules from master, #162797a453e89ea3518f8a9a876246c25303b643

Here's the tasks:
```yaml
 - name: create primary sqlserver
   azure_rm_sqlserver:
     location: "{{ az_region }}"
     admin_username: "{{ primary_sqlserver_user }}"
     admin_password: "{{ primary_sqlserver_password }}"
     name: test-web-sqlserver-01
     resource_group: "{{ resource_group }}"
 - name: create primary database elastic pool
   azure_rm_sqlelasticpool:
     location: "{{ az_region }}"
     name: test-web-edp-pool-01
     profile: "{{ az_profile }}"
     resource_group: "{{ resource_group }}"
     server_name: test-web-sqlserver-01
     dtu: 100
     storage_mb: 15000
     zone_redundant: false
     edition: standard
 - name: create primary sql database
   azure_rm_sqldatabase:
     create_mode: copy
     elastic_pool_name: test-web-edp-pool-01
     location: "{{ az_region }}"
     name: test-web-edp-01
    resource_group: "{{ resource_group }}"
     server_name: test-web-sqlserver-01
     source_database_id: "{{ copy_source_id }}"
```
Expected behavior:
db test-web-edp-01 should be in pool test-web-edp-pool-01

Actual result:
test-web-edp-pool-01 pool has no databases and test-web-edp-01 is not associated with any pools.
