### ISSUE TITLE
Inconsistent authorization between az_rm_dnsrecordset_facts and az_rm_dnsrecordset

### ISSUE THREAD

**Issue by jdashton** [Azure/azure_preview_modules#279]
When I perform this action, the credentials in use have sufficient authorization:
```
  module_defaults:
    group/azure:
      resource_group: nad-core
      subscription_id: "{{ azuredns_subscriptionid }}"
      client_id: "{{ azuredns_appid }}"
      secret: "{{ azuredns_clientsecret }}"
      tenant: "{{ azuredns_tenantid }}"

  tasks:
    - name: Get Azure DNS Zone facts
      azure_rm_dnsrecordset_facts:
        zone_name: hope4humanity.info
        relative_name: 'jda'
        record_type: A
```
But when I perform this action with the same credentials on the same resource_group, zone_name, relative_name and record_type, I get an error about not having "read" authorization on the resource_group:
```
  module_defaults:
    group/azure:
      resource_group: nad-core
      subscription_id: "{{ azuredns_subscriptionid }}"
      client_id: "{{ azuredns_appid }}"
      secret: "{{ azuredns_clientsecret }}"
      tenant: "{{ azuredns_tenantid }}"

  tasks:
    - name: Get Azure DNS Zone facts
      azure_rm_dnsrecordset:
        zone_name: hope4humanity.info
        relative_name: 'jda'
        record_type: A
        records:
          - entry: 192.168.100.101
```
The service principal has limited authorization to do anything and everything with four specific domains out of a larger resource group. Clearly, from the first example above, it has sufficient authorization to read records. Why does this error message about "read" authorization come up when using the same credentials?
```
"msg": "Error retrieving resource group nad-core - The client '810b4e57-8616-4e20-bf8f-de89127fa05d' with object id '810b4e57-8616-4e20-bf8f-de89127fa05d' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/3f4c0514-e03d-4bdd-9572-c7b33fd31905/resourcegroups/nad-core'."
```
The service principal was created with this command:
```
az ad sp create-for-rbac --name  "AcmeDnsValidator" --role "DNS Zone Contributor" --scopes scope1 scope2 etc
```
The scopes in this command pointed to the four specific DNS zones within the larger resource group.

Also, the same credentials are sufficient, when used with [acme.sh](https://github.com/Neilpang/acme.sh), to create DNS records in these zones.
