### ISSUE TITLE
Modules ignore `subscription_id` when using CLI auth

### ISSUE THREAD

**Issue by UnwashedMeme** [Azure/azure_preview_modules#321]
A playbook, e.g.
```
- name: Create Azure VMs
  strategy: free
  hosts:
    - localhost
  gather_facts: false

  roles:
    - { role: azure.azure_preview_modules }
  tasks:
    - name: "Create Resource group"
      delegate_to: localhost
      azure_rm_resourcegroup:
        name: "foobar"
        location: "eastus2"
        auth_source: cli
        subscription_id: "ecb1bdd8-..."
```
Ignores the `subscription_id` field:

```
$ az account list --verbose --query '[*].{id:id,isDefault:isDefault,state:state}'
[
  {
    "id": "f1c043c7-...",
    "isDefault": true,
    "state": "Enabled"
  },
  {
    "id": "ecb1bdd8-...",
    "isDefault": false,
    "state": "Enabled"
  }
]

$ ansible-galaxy install --force azure.azure_preview_modules                                                                                                                                                      
- changing role azure.azure_preview_modules from 2.8.0 to unspecified                                                                                                                                             
- downloading role 'azure_preview_modules', owned by azure                                                                                                                                                        
- downloading role from https://github.com/Azure/azure_preview_modules/archive/2.9.0.tar.gz                                                                                                                       
- extracting azure.azure_preview_modules to ~/.ansible/roles/azure.azure_preview_modules                                                                                
- azure.azure_preview_modules (2.9.0) was installed successfully                                           

$ ansible-playbook -v subtest.yml
PLAY [Create Azure VMs] *******************************************************************************************************************************************************************************************

TASK [azure.azure_preview_modules : debug] ************************************************************************************************************************************************************************
skipping: [localhost] => 

TASK [Create Resource group] **************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => changed=false 
  contains_resources: false
  state:
    id: /subscriptions/f1c043c7-.../resourceGroups/foobar
    location: eastus2
    name: foobar
    provisioning_state: Succeeded
    tags: {}

```

Note that even though I specifically asked for the rg to be created in "ecb1bdd8-..." it was created in "f1c043c7-...". 

This is especially frustrating when dealing with things that span multiple subscriptions. E.g. I want to look up vnet facts in one subscription to use it for a VM on the other subscription. Or I have a playbook that is creating a VM on each subscription.

My work around at the moment is: 
```
    - name: "Ensure the correct subscription"
      delegate_to: localhost
      shell: "az account set -s {{ subscription }}"
```
but this fails when trying to run for multiple inventory items simultaneously (e.g. build 1 vm on each vm).
