### ISSUE TITLE
azure_rm_keyvaultsecret failure using keyvault==1.1.0

### ISSUE THREAD

**Issue by ihegmanns** [Azure/azure_preview_modules#324]
azure_rm_keyvaultsecret faces a problem with azure-keyvault==1.1.0.

Issue: Deleting a non existent secret as well as adding an already existing secret (so when result would be ok and not changed) fails with following error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'KeyVaultErrorException' is not defined
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1571911117.28-185467568576007/AnsiballZ_azure_rm_keyvaultsecret.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1571911117.28-185467568576007/AnsiballZ_azure_rm_keyvaultsecret.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1571911117.28-185467568576007/AnsiballZ_azure_rm_keyvaultsecret.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_nXJ678/__main__.py\", line 226, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_nXJ678/__main__.py\", line 222, in main\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_nXJ678/__main__.py\", line 125, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_nXJ678/ansible_azure_rm_keyvaultsecret_payload.zip/ansible/module_utils/azure_rm_common.py\", line 325, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_nXJ678/__main__.py\", line 145, in exec_module\nNameError: global name 'KeyVaultErrorException' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Test case:

- Prerequisite:
    - key vault exists and access by ansible is possible, i.e. credentials known or msi setup
    - key does not exist 
- Test code:
```
    - name: "Test delete"
      azure_rm_keyvaultsecret:
        client_id: "<parameter>"
        subscription_id: "<parameter>"
        secret: "<parameter>"
        tenant: "<parameter>"
        secret_name: "a-test-secret"
        keyvault_uri: "https://<keyvaultname>.vault.azure.net/"      
        state: absent
      delegate_to: localhost  
``` 

Expected result: ok (nothing changed as key does not exist)
Experienced result: NameError: global name 'KeyVaultErrorException' is not defined

Issue exists with: azure-keyvault==1.1.0.
Issue does not exist with azure-keyvault==1.0.0a1

Hint: Not sure but problem seems to be related to:
`from azure.keyvault.models.key_vault_error import KeyVaultErrorException`
where in 1.1.0 I think it is:
`from azure.keyvault.v7_0.models.key_vault_error import KeyVaultErrorException`

Possible solution? As a beginner in Python I could think about following (Try to support keyvault==1.1.0 and later, fallback keyvault==1.0.0a1)
```
try:
  from azure.keyvault.v7_0.models.key_vault_error import KeyVaultErrorException
except ImportError:
  try:
    from azure.keyvault.models.key_vault_error import KeyVaultErrorException
```

Versions:
ansible 2.8.6
python version = 2.7.15+
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
azure-keyvault==1.0.0a1 / azure-keyvault==1.1.0
azure-mgmt-keyvault==1.1.0
Ubuntu 18.04.1 LTS
