### ISSUE TITLE
azure_rm_virtualmachine zones parameter does not support zone/non-zone in same template

### ISSUE THREAD

**Issue by wrprice** [Azure/azure_preview_modules#361]
The current handling for the `zones` parameter in `azure_rm_virtualmachine.py` makes it difficult to write a single template which works for zonal and non-zonal VMs (i.e. depending on an input variable).  The module currently, and correctly, mimics the [ARM template schema][arm-vm-spec]:

Name | Type | Required | Value
-- | -- | -- | --
zones | array | No | The virtual machine zones. - string

I'm at a loss why ARM has zones (plural) when it seems as though a VM can be either non-zonal or in a single zone.  In any case, the Ansible module similarly expects an array of string as input:

```
- name: Virtual Machine
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ rg_name }}"
    zones: [ "1" ]
    #...
```

If one desires a non-zonal VM, the `zones` parameter **must be omitted completely**.  This is because of how this parameter is handled on [line 949][vmpy-L949]:

```
self.zones = [int(i) for i in self.zones] if self.zones else None
```

Whereas the [_azure_rm_manageddisk_][diskpy-zone] module [supports the empty string][diskpy-L212] `''` (though inconsistently [documented as a space][diskpy-space] instead of empty), this module does not accept strings which are not integers.  Empty and non-integer string values result in the error:

> azure_rm_virtualmachine.py, line 951, in exec_module
> ValueError: invalid literal for int() with base 10: ''

Using a bogus value, like `0` specifically in a region without zone support results in:

> FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine vmname - Azure Error: LocationNotSupportAvailabilityZones\nMessage: The resource 'Microsoft.Compute/virtualMachines/vmname' does not support availability zones at location 'westus'."}

The only workaround I can currently think of is to declare two tasks with nearly identical configurations, with the exception of `zones`, and use a `when` condition.  But this workaround creates a maintenance headache to mirror changes to other parameters twice.

Please consider updating the module to interpret the empty string in the `zones` list as requesting _no zone assignment_ to ease templating and for better consistency with the `azure_rm_manageddisks` module.

[arm-vm-spec]: https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2018-10-01/virtualmachines#property-values
[vmpy-L949]: https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_virtualmachine.py#L949
[diskpy-zone]: https://docs.ansible.com/ansible/latest/modules/azure_rm_manageddisk_module.html#parameter-zone
[diskpy-L212]: https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_manageddisk.py#L212
[diskpy-space]: https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_manageddisk.py#L111

**Comment by Fred-sun** [comment]
@wrprice Thank you for taking the time to report this problem. You are welcome to send PR for the problems mentioned above.

**Comment by wrprice** [comment]
I found a workaround, so I will close this issue:

```
tasks:
- name: workaround
  vars: # the following var is defined for clarity; it can be inherited instead
    zone: 0   #  use 1, 2, 3 for zonal; or 0/undefined for non-zonal
  azure_rm_virualmachine:
    zones: "{{ [ '' ~ zone ] if (zone|default(0) > 0) else omit }}"
```
