### ISSUE TITLE
azure_rm_virtualmachine does not support creating VM and attaching existing data disk

### ISSUE THREAD

**Issue by wrprice** [Azure/azure_preview_modules#362]
There is an [example][line464] in the documentation, see `lun: 0`:

```
- name: Create a VM with OS and multiple data managed disks
  azure_rm_virtualmachine:
    # ...
    data_disks:
      - lun: 0
        managed_disk_id: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myDisk"
      - lun: 1
        disk_size_gb: 128
        managed_disk_type: Premium_LRS
```

This appears to be a missing feature.  The `managed_disk_id` property is not defined in the documentation, and the only use in the module source code appears to be for deleting VMs and their resources.  On create, the following error is observed:

> azure_rm_virtualmachine.py, line 1414, in exec_module
> KeyError: 'disk_size_gb'

This is a necessary feature so that data disks can be attached at VM creation time and available for other provisioning tasks which run immediately on the VM (e.g. cloud-init).  Alternatively, all data disks needed during initial provisioning must be created new, by this module, as in the example above for `lun: 1` and cannot use an existing disk.  Using other modules to attach a data disk _after_ the VM has been provisioned is possible, as long as the disk is not needed during initial provisioning.

[line464]: https://github.com/Azure/azure_preview_modules/blob/354baf42ae4e571e5e788d03ef6a3ef267d9377f/library/azure_rm_virtualmachine.py#L464
