### ISSUE TITLE
Unable to create a azure_rm_networkinterface with private only IP config

### ISSUE THREAD

**Issue by dedickinson** [Azure/azure_preview_modules#85]
I'm trying to setup a `azure_rm_networkinterface` with a static private IP address and no Public IP address. However, I get the following error:

    msrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None.

Sample task:
```
- name: Create the  NIC
  azure_rm_networkinterface:
    name: "MyTestNic"
    resource_group: "demo"
    security_group_name: "nsg-private"
    subnet_name: "private"
    ip_configurations:
      - name: primary
        private_ip_allocation_method: Static
        private_ip_address: "172.16.1.42"
        primary: True
    virtual_network_name: "vnet-demo"
```

Note that I get the same error when I remove the `private_ip_allocation_method` and `private_ip_address` elements.

Full error output:
````
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 595, in <module>\n    main()\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 591, in main\n    AzureRMNetworkInterface()\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 408, in __init__\n    required_if=required_if)\n  File \"/tmp/ansible_5ynwcvi_/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 345, in __init__\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 516, in exec_module\n    ) for ip_config in self.ip_configurations\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 516, in <listcomp>\n    ) for ip_config in self.ip_configurations\n  File \"/tmp/ansible_5ynwcvi_/ansible_module_azure_rm_networkinterface.py\", line 546, in get_or_create_public_ip_address\n    poller = self.network_client.public_ip_addresses.create_or_update(self.resource_group, name, params)\n  File \"/usr/local/lib/python3.5/dist-packages/azure/mgmt/network/v2017_06_01/operations/public_ip_addresses_operations.py\", line 212, in create_or_update\n    'publicIpAddressName': self._serialize.url(\"public_ip_address_name\", public_ip_address_name, 'str'),\n  File \"/usr/local/lib/python3.5/dist-packages/msrest/serialization.py\", line 488, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/usr/local/lib/python3.5/dist-packages/msrest/serialization.py\", line 558, in validate\n    raise ValidationError(\"required\", name, True)\nmsrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
````

**Comment by Fred-sun** [comment]
Hi @dedickinson ,I have tried to setup a azure_rm_networkinterface with a static private IP address and no Public IP address.  But get successfully result, could you help check your ansible version ,Another, could you update ansible to 2.5.5 ( sudo pip install ansible[azure]==2.5.5) and retry your yml ， My yml script ,execute result as below. Thanks !
``` e.g.
Yml script:
---
- name: For test 85
  hosts: localhost
  connection: local
  vars:
    resource_group: myRG
    location: westeurope
    virtualnetwork: virtualnetwork
    subnet: subnet
    public_ip: public_ip
    security_ssh: security_ssh
    test_nic: test_nic
    vm_name: myVM
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "172.16.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "172.16.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
 
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      subnet: "{{ subnet }}"
      security_group_name: "{{ security_ssh }}"
      ip_configurations:
        - name: primary
          private_ip_allocation_method: Static
          private_ip_address: '172.16.1.42'
          primary: True
      virtual_network_name: "{{ virtualnetwork }}"
    register: nic_dump
  - name: dump nic data
    debug:
      var: nic_dump

Execute result:
TASK [Create NIC] **************************************************************
ok: [127.0.0.1]

TASK [dump nic data] ***********************************************************
ok: [127.0.0.1] => {
    "nic_dump": {
        "changed": false, 
        "failed": false, 
        "state": {
            "dns_settings": {
                "applied_dns_servers": [], 
                "dns_servers": [], 
                "internal_dns_name_label": null, 
                "internal_fqdn": null
            }, 
            "enable_ip_forwarding": false, 
            "etag": "W/\"636ecf84-ec44-42af-8e79-b8ba8c915738\"", 
            "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkInterfaces/test_nic", 
            "ip_configuration": {
                "name": "primary", 
                "primary": true, 
                "private_ip_address": "172.16.1.42", 
                "private_ip_allocation_method": "Static", 
                "public_ip_address": null, 
                "subnet": {
                    "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/virtualnetwork/subnets/subnet", 
                    "name": "subnet", 
                    "resource_group": "myRG", 
                    "virtual_network_name": "virtualnetwork"
                }
            }, 
            "ip_configurations": [
                {
                    "name": "primary", 
                    "primary": true, 
                    "private_ip_address": "172.16.1.42", 
                    "private_ip_allocation_method": "Static", 
                    "public_ip_address": null, 
                    "subnet": {
                        "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/virtualnetwork/subnets/subnet", 
                        "name": "subnet", 
                        "resource_group": "myRG", 
                        "virtual_network_name": "virtualnetwork"
                    }
                }
            ], 
            "location": "westeurope", 
            "mac_address": null, 
            "name": "test_nic", 
            "network_security_group": {
                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Network/networkSecurityGroups/security_ssh", 
                "name": "security_ssh"
            }, 
            "provisioning_state": "Succeeded", 
            "tags": {}, 
            "type": "Microsoft.Network/networkInterfaces"
        }
    }
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=8    changed=0    unreachable=0    failed=0

**Comment by Fred-sun** [comment]
Hi @dedickinson ，Does you still have this question, if have, could you update your ansible and try again, Please let me kwon your result. Thanks a lot!

**Comment by dedickinson** [comment]
My sincere apologies - I hadn't seen the update. I will attempt to test this over the coming week.

**Comment by dedickinson** [comment]
Hi - I finally got around to testing - sorry for the delay.

I can confirm that I can now create a NIC with a static private IP and no public IP

I ran the playbook in Azure Cloud Shell with Ansible 2.6.1:

````
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/duncan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
````

My playbook was as follows:

````yaml
---
- name: For test 85
  hosts: localhost
  connection: local
  vars:
    resource_group: lab-vnet
    location: australiaeast
    virtualnetwork: labnet
    subnet: private
    nsg: private-nsg
    security_ssh: security_ssh
    test_nic: test_nic
  tasks:
  - name: Create the  NIC
    azure_rm_networkinterface:
        name: "MyTestNic"
        resource_group: "{{ resource_group }}"
        security_group_name: "{{ nsg }}"
        subnet_name: "{{ subnet }}"
        ip_configurations:
            - name: primary
              private_ip_allocation_method: Static
              private_ip_address: "10.0.2.20"
              primary: True
        virtual_network_name: "{{ virtualnetwork }}"
    register: nic_dump
  - name: dump nic data
    debug:
      var: nic_dump
````
